sonar.projectKey=abvgzxn_frontend-project-11
sonar.organization=abvgzxn

sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, **/*.test.js
sonar.javascript.file.suffixes=.js,.jsx,.mjs